### ISSUE TITLE
Failed to login to carnet, 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by thomastitze** [robinostlund/volkswagencarnet#116]
tried to use the new version and get the following messages:
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:volkswagencarnet:Using service <https://www.portal.volkswagen-we.com/>
ERROR:volkswagencarnet:Failed to login to carnet, 'NoneType' object has no attribute 'group'

Any idea what this could be?

**Comment by haeuslesbauer** [comment]
Exactly the same problem here as described in  issue #111 which was closed a few days ago. But after upgrading the volkswagencarnet package via pip3 the above error still exists

**Comment by thomastitze** [comment]
Had a chance now to debug a little bit deeper. Found a problem in the token and needed to change this in the code
 async def validate_tokens(self):
        """Function to validate expiry of tokens."""
        ###idtoken = self._session_tokens['identity']['id_token']
        idtoken = self._session_tokens['Legacy']['id_token']
        ###atoken = self._session_tokens['vwg']['access_token']
        atoken = self._session_tokens['Legacy']['access_token']
        id_exp = jwt.decode(idtoken, verify=False).get('exp', None)
        at_exp = jwt.decode(atoken, verify=False).get('exp', None)

Seems that the token format is different in my case, I get a "Legacy" token instead of "identity". Tested it also with a newly created user but same result. With this change login is successful but the list of vehicles returned is empty. So still no possibility to download the vehicle information.

**Comment by thomastitze** [comment]
After some more debugging I found out the connection.doLogin() seems to be the right method to call instead of connection._login() shown in the example. With the change from the comment before and the doLogin change I do get now all data from my car :-)

**Comment by thomastitze** [comment]
Last update, with the doLogin method the token contains "Legacy" and "identity" fields. With this everything seems to work. Should the example file be updated?

**Comment by jannegpriv** [comment]
Which jwt package should you use? I've tried with PyJWT 2.1.0 but it then fails during decode:
`WARNING:vw_connection:Could not update information: It is required that you pass in a value for the "algorithms" argument when calling decode().`
