### ISSUE TITLE
Range not available anymore

### ISSUE THREAD

**Issue by amueller-tech** [robinostlund/volkswagencarnet#123]
Hi, 
I currently upgraded to the latest master and I'm not getting the electric range anymore.
It used to be available via "sensor.eup_combustion_range", but this entity is no longer updated.

**Comment by amueller-tech** [comment]
This sensor is not being created anymore.
After the switch to the mobile API the electric range was available via _combustion_range

**Comment by JohNan** [comment]
@amueller-tech What car du you have and can you provide some logs?

**Comment by amueller-tech** [comment]
It's a VW eUP.
Looking at the logs I see the following:

The electric range is supported and it's correctly retrieved from the server:

```
 [vw_dashboard] WVWXXXXX Electric range is supported
 [vw_dashboard] WVWXXXXX Combustion range (Sensor:combustion_range) is not supported
...
primaryEngineRange': {'content': 217, 'timestamp': datetime.datetime(2021...)
```

Once homeassistant is then setting up and populating the sensors here:
```
[homeassistant.components.binary_sensor] Setting up binary_sensor.volkswagencarnet
```
there's no such entry for the range, but for all other sensors such as:
```
[custom_components.volkswagencarnet.sensor] Getting state of battery_level
home-assistant      | 2021-05-12 08:32:23 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.eup_battery_level, ...
```

**Comment by zzarne** [comment]
Have you tried removing (Settings->Integrations) and adding the integration? The configuration of the entities provided by the integration are only selectable when adding it.

**Comment by amueller-tech** [comment]
That helped, thanks a lot! 
- why didn't I think of this.... was of the opinion that it gets populated on every restart.
