### ISSUE TITLE
Feature Request: Action - Change Maximum Charge Current

### ISSUE THREAD

**Issue by rreinhardd** [robinostlund/volkswagencarnet#13]
Hi Robin, I really enjoy using your library in Home-Asisstant. Would it be possible to make an Action to change the maximum charging current of the car (where applicable)? In the WeConnect-App this is possible just as i can start Climatisation.

The Use-Case for this for me is the following. I have a PV-Generator on my roof and depending on Power from the Sun, i would like to charge either with 5 or 10 Ampere (Possible Steps in the APP: 5, 10, 13, MAX). Here are the Screenshots from the WeConnect APP:

Best, Reinhard

![7EFB687B-55F6-4FBC-A6B9-8F12809749F3](https://user-images.githubusercontent.com/46643626/79119068-bfce8700-7d8f-11ea-872c-0cf114a9b28b.jpeg)

![03C0BD84-FC06-4B70-9756-E6A3CF4583DF](https://user-images.githubusercontent.com/46643626/79119649-21dbbc00-7d91-11ea-88b4-18b2a7b357d4.jpeg)

**Comment by robinostlund** [comment]
Yes i think so :) i will check this once i have time :)

**Comment by ottoba** [comment]
@rreinhardd I wanted the same feature, and actually ended up using this repository: https://github.com/trocotronic/weconnect

I added to 'WebAPI' the following code:

    # set maximum charge current in Ampere, allowed values for e-golf: 5, 10, 13, and 'max', beware that you can only change this a number of times, else VW will return 429 error 'too many requests'
    def set_charger_max_current(self, chargerMaxCurrent='max'):
        self.__check_dashboard()
        self.__command('/-/emanager/set-settings', post={ "chargerMaxCurrent": chargerMaxCurrent, "minChargeLimit": None, "climatisationWithoutHVPower": None, "targetTemperature": None })
 
And that works! You can probably do something similar for Robin's API implementation.

**Comment by thomaskien** [comment]
@ottoba are you by now able to set the charger current via the native api now?

**Comment by Langer75** [comment]
think this works only with the Web API which is not working any more. So I would also like to have the possibility to change the max charging current. Does anybody has a solution for that with the new API?

**Comment by Langer75** [comment]
As I studied the code set max charger current is implemented. The one thing that is missing is the connection to homeassistant. I have coded a small client script to use the library via command line. [volkswagencarnet-client](https://github.com/Langer75/volkswagencarnet-client)

**Comment by milkboy** [comment]
Maybe something like this?
![image](https://user-images.githubusercontent.com/1941814/155712288-d3a4b9a9-c2bb-4b38-9cdb-d69aa7dd5c03.png)

**Comment by milkboy** [comment]
[v4.4.49](https://github.com/robinostlund/volkswagencarnet/releases/tag/v4.4.49) contains the functionality to change manuallr started charges in [vw_vehicle.py](https://github.com/robinostlund/volkswagencarnet/blob/5ae609fb182b1a8132bc38f20903be1a030f2081/volkswagencarnet/vw_vehicle.py#L302) and defining the [departure timers](https://github.com/robinostlund/volkswagencarnet/blob/5ae609fb182b1a8132bc38f20903be1a030f2081/volkswagencarnet/vw_connection.py#L1069) etc
