### ISSUE TITLE
Is auxiliary heating confirmed working?

### ISSUE THREAD

**Issue by birgersp** [robinostlund/volkswagencarnet#135]
Hi,

Maybe I am misinterpreting things. But auxiliary heating is an "extra" heating function on some cars, where there is a fuel burner that can heat up the car while the car is parked. Right? Like shown here: https://www.youtube.com/watch?v=hfX2KSdKQBc
![image](https://user-images.githubusercontent.com/5260237/142195116-2121291a-14cb-445c-8780-99d25a355863.png)

One of my cars has the auxiliary heater installed. I can activate it either from the button inside my car or this separate remote that we got with the car. But I have not been able to find how to activate it through the WeConnect app, nor the official Volkswagen We Connect website.

I tried using this python library to activate the auxiliary heater, but I got an error saying that I was not authorized (even though login, status update was ok and my SPIN is verified correct).

Is auxiliary heating actually something that can be activated via the web portal?
Has someone tested and confirmed enabling it through this python library?

Or is it just my car that doesn't have the ability to activate it through the web services...

**Comment by odelma** [comment]
Hi,

we have a -19 VW Passat with auxiliary heater (can be started from the app or from the remote) and it is working through the Home Assistant integration (which is using this library). But turn off function is not working (it is possible to turn it of via the app). I also seem to have some issues with the number of avaialble requests that has caused problems in setting the function when needed:
![image](https://user-images.githubusercontent.com/10372952/143404758-0844a5cc-5a02-47ca-9282-541f4e517b1a.png)
it seems that the number of available requests suddenly drops to -1 and then remote calls are not working anymore.

**Comment by birgersp** [comment]
Ok, thanks. Then probably it's just my model (2018 Passat) that doesn't have this function.

Would you care to share a screenshot of the (official) app where the auxiliary heating button is shown? Is it the same place as the rest (AC, window heating, etc)?

**Comment by odelma** [comment]
Sure:
![4ED1638E-B816-4ABC-93AA-B2F3D0D9A016](https://user-images.githubusercontent.com/10372952/143410496-819f30df-5695-4896-b18e-3cab9c9aedd9.jpeg)
![3AE218AC-45A2-4B42-AB79-96D9E1740FE4](https://user-images.githubusercontent.com/10372952/143410536-709009dd-ce84-4b7b-8dc6-acc9dd442439.jpeg)

**Comment by birgersp** [comment]
Thank you for sharing those! Then definitely the conclusion is that my car doesn't have this remote auxiliary heating feature available. It looks different for me, there is climate control, charging, etc where you have the auxiliary option.
