### ISSUE TITLE
No data for two or more vehicles with different homeregion

### ISSUE THREAD

**Issue by boanjo** [robinostlund/volkswagencarnet#136]
I have one Tiguan and used it in the homeassistant plugin successfully for a year. During the fall i picked up a new Passat GTE and then the plugin started to behave a bit erratic. Most of the time it only impacted the Tiguan but also sometimes the other which then seems to have some timing to it. Most of the time the Tiguan shows that is has 4 entities (sensors)

I've now found some time to troubleshoot the rootcause and it seems to originate from the fact that the home region are different for my two vehicles (fal-1a vs fal-3a). The weird part is that using the "wrong" homeregion base url does actually return something but only a subset of all the services and sensors. 

In the vw_connection.py when the getHomeRegion is called returns two different strings that is stored in the vw_vehicle but is not used anymore. But the connection stores self._session_spin_ref_url and others that are overwitten for every vehicle to be used later for requests. 

A quick fix for me has been to just run the connection.update of vehicles in sequence rather in async
  for vehicle in self.vehicles: 
     vehicle.update()
 
I also made an attempt to use the homeregion per vehicle but then the _make_url and other functions started to feel like they should be per vehicle. There are also some hairy replace of 'mal-' to 'fal-' with hardcoded "1a" (https://mal-1a.prd.ece.vwg-connect.com/api) i don't really understand and might apply to "3a" links. 

I will continue to implement a more sustainable solutions (maybe there are not too many that have more than one vehicle and that are different home region and that use this SW...) but any ideas are welcome. Also any insights on the story around the mal fal replace or that just comes from empirical testing.

**Comment by milkboy** [comment]
Fixed by #142
