### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by Langer75** [robinostlund/volkswagencarnet#137]
Hey folks

Today the login crashed with the following error:
**DEBUG:vw_connection:Using service https://msg.volkswagen.de
DEBUG:vw_connection:Initiating new login
DEBUG:vw_connection:Got authorization endpoint
ERROR:vw_connection:Failed to extract password login form.
ERROR:vw_connection:Login failed for VW account, 'NoneType' object has no attribute 'find_all'
ERROR:vw_connection:'NoneType' object has no attribute 'find_all'
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/vw_connection.py", line 254, in _login
    raise e
  File "/home/pi/.local/lib/python3.7/site-packages/vw_connection.py", line 249, in _login
    response_soup.find('form', id='credentialsForm').find_all('input', type='hidden')])
AttributeError: 'NoneType' object has no attribute 'find_all'
INFO:vw_connection:Something failed**

A friend got the same messages. Does anybody else has such problems? The response from the server seems some how currupted.

**Comment by thomaskien** [comment]
everybody, other projects like https://github.com/tillsteinbach and https://github.com/evcc-io/evcc also had to fix the vw changes.

**Comment by andig** [comment]
See https://github.com/evcc-io/evcc/pull/2430/files. Page is built dynamically now.

**Comment by milkboy** [comment]
Meh.. Tried to just fix it, but getting "HTTP 400" from the service...

**Comment by andig** [comment]
You still need to send the exact same request as before.

**Comment by milkboy** [comment]
yea.. had one stupid typo

**Comment by tubalainen** [comment]
And SPIN looks like an issue - fails when called :/
https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/353#issuecomment-1024924194

**Comment by milkboy** [comment]
`fromhex() argument must be str, not int`

**Comment by milkboy** [comment]
> `fromhex() argument must be str, not int` Maybe just my local setup though

yea. managet to get the 403 also now.. :safety_pin:

**Comment by Farfar** [comment]
> And SPIN looks like an issue - fails when called :/ [robinostlund/homeassistant-volkswagencarnet#353 (comment)](https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/353#issuecomment-1024924194)

Take a look at your config. There's no problem with S-PIN auth for Skoda Connect which this shares a large part of the codebase with. Unless the code relevant for handling S-PIN changed it should work.
It's the last step that fails in your debug and it might be a server-side problem also.

**Comment by tubalainen** [comment]
Hej Farfar. Ive changed nothing but the vw_connection.py file - my setup and config is identical and it all worked perfect until I restarted and initiated the PR version of the new vw_connection.py file. Looks like @milkboy also got the same issue.

**Comment by Farfar** [comment]
> Hej Farfar. Ive changed nothing but the vw_connection.py file - my setup and config is identical and it all worked perfect until I restarted and initiated the PR version of the new vw_connection.py file. Looks like @milkboy also got the same issue.

Does it matter which function you use? Aux heater/lock/unlock?

**Comment by tubalainen** [comment]
> > Hej Farfar. Ive changed nothing but the vw_connection.py file - my setup and config is identical and it all worked perfect until I restarted and initiated the PR version of the new vw_connection.py file. Looks like @milkboy also got the same issue.
> 
> Does it matter which function you use? Aux heater/lock/unlock?

Nopp - same debug error on SPIN - but different error from the different entities.

**Comment by milkboy** [comment]
Okay, so only one request to start the spin auth is allowed / x time. After that, all calls return 403 for a while.. Additionally I have some issues with the We Connect app on my backup phone.. it crashes on startup after showing a "INVALID_SERVICE" message for a while.. no idea when that broke though.

**Comment by milkboy** [comment]
Anyway, should we open a separate issue for the SPIN problem?

**Comment by tubalainen** [comment]
If you are all out of "allowed interactions" you need to go for a drive around the block whilst listening to Lordi on full blast. ;)
The you will get rewarded with 15 new interactions.
