### ISSUE TITLE
User appears unauthorized

### ISSUE THREAD

**Issue by Langer75** [robinostlund/volkswagencarnet#200]
does anybody have this new issue?

ERROR:vw_connection:Login failed for VW account, User appears unauthorized
ERROR:vw_connection:User appears unauthorized
Traceback (most recent call last):
  File "/home/pi/vw_connection.py", line 328, in _login
    raise e
  File "/home/pi/vw_connection.py", line 305, in _login
    raise Exception("User appears unauthorized")
Exception: User appears unauthorized

**Comment by robinostlund** [comment]
Have you logged in to myvolkswagen and checked if there are any new agreements to approve? I had to do that today 😊

**Comment by Langer75** [comment]
Yes that's it. Just one login and it works again. thanks

**Comment by robinostlund** [comment]
@wss2 check my reply above
