### ISSUE TITLE
Failed to fetch VW-Group API tokens, API token request returned with status code 403

### ISSUE THREAD

**Issue by haeuslesbauer** [robinostlund/volkswagencarnet#208]
This script run for 2+ years without problems. But since a few weeks only 1 out of 20 runs were successful. So i thought it would be a good idea to update this library and downloaded the source / installed V4.4.61.

Now i get always the same error and i am no longer able to fetch the data. 

DEBUG:asyncio:Using selector: EpollSelector
DEBUG:vw_connection:Using service https://msg.volkswagen.de
DEBUG:vw_connection:Initiating new login
DEBUG:vw_connection:Got authorization endpoint
DEBUG:vw_connection:Authenticating with email and password.
DEBUG:vw_connection:Parsing login response.
DEBUG:vw_connection:Login successful, received authorization code.
DEBUG:vw_connection:Trying to fetch user identity tokens.
DEBUG:vw_connection:User identity token verified OK.
INFO:vw_connection:Successfully logged in
DEBUG:vw_connection:Trying to fetch api tokens.
DEBUG:vw_connection:API token request failed.
ERROR:vw_connection:Failed to fetch VW-Group API tokens, API token request returned with status code 403

I am still able to login to the We Connect app and see the data there as well to the VW portal.
Any idea whats wrong here?

**Comment by stickpin** [comment]
Same story in Home Assistant. 
Today not able to make it work at all. :(
WeConnect App works fine.

```
2023-09-01 17:42:26.390 INFO (MainThread) [volkswagencarnet.vw_connection] Successfully logged in
2023-09-01 17:42:26.416 ERROR (MainThread) [volkswagencarnet.vw_connection] Failed to fetch VW-Group API tokens, API token request returned with status code 403
2023-09-01 17:42:26.417 ERROR (MainThread) [custom_components.volkswagencarnet.config_flow] Failed to login due to error: 'vwg'
```

**Comment by beschoenen** [comment]
Did some research on this, and seems like the hardcoded client id `XCLIENT_ID` is expired on VW's side.
I generated a new one using a snipper from weconnect, and it the example file from the readme works again now.

```
diff --git a/volkswagencarnet/vw_const.py b/volkswagencarnet/vw_const.py
index a63951e..f64528d 100644
--- a/volkswagencarnet/vw_const.py
+++ b/volkswagencarnet/vw_const.py
@@ -28,7 +28,7 @@ CLIENT = {
 }
 
 
-XCLIENT_ID = "85fa2187-5b5c-4c35-adba-1471d0c4ea60"
+XCLIENT_ID = "c8fcb3bf-22d3-44b0-b6ce-30eae0a4986f"
 XAPPVERSION = "5.3.2"
 XAPPNAME = "We Connect"
 USER_AGENT = "okhttp/3.14.7"
 ```

weconnect has an interesting approach generating a new client for each session, maybe that's something we should implement, too.
Check out this snippet to see how it works.
https://github.com/trocotronic/weconnect/blob/master/NativeAPI.py#L429-L442

**Comment by stickpin** [comment]
> Did some research on this, and seems like the hardcoded client id `XCLIENT_ID` is expired on VW's side. I generated a new one using a snippet from weconnect, and the example file from the readme works again now.
> 
> ```
> diff --git a/volkswagencarnet/vw_const.py b/volkswagencarnet/vw_const.py
> index a63951e..f64528d 100644
> --- a/volkswagencarnet/vw_const.py
> +++ b/volkswagencarnet/vw_const.py
> @@ -28,7 +28,7 @@ CLIENT = {
>  }
>  
>  
> -XCLIENT_ID = "85fa2187-5b5c-4c35-adba-1471d0c4ea60"
> +XCLIENT_ID = "c8fcb3bf-22d3-44b0-b6ce-30eae0a4986f"
>  XAPPVERSION = "5.3.2"
>  XAPPNAME = "We Connect"
>  USER_AGENT = "okhttp/3.14.7"
> ```
> 
> weconnect has an interesting approach generating a new client for each session, maybe that's something we should implement, too. Check out this snippet to see how it works. https://github.com/trocotronic/weconnect/blob/master/NativeAPI.py#L429-L442
> 
> Proof:
> 
> ```
> name: WVWZZZAUZJW80**** Service inspection days
> str_state: -4 days
> state: -4
> supported: True
> attr: service_inspection
> attributes: {}
> name: WVWZZZAUZJW80*** Charging time left
> str_state: 0 min
> state: 0
> supported: True
> attr: charging_time_left
> attributes: {}
> name: WVWZZZAUZJW80*** Combustion range
> str_state: 520 km
> state: 520
> supported: True
> attr: combustion_range
> attributes: {}
> ```

I can confirm that the new client ID also works for me. 
Thanks @beschoenen!

**Comment by StefanoGiu** [comment]
Hi all, I changed the XCLIENT_ID to "c8fcb3bf-22d3-44b0-b6ce-30eae0a4986f". With the integration "Volkswagen WeConnect" I still get the below error:

[volkswagencarnet.vw_connection] Failed to fetch VW-Group API tokens, API token request returned with status code 403

**Comment by stickpin** [comment]
> Hi all, I changed the XCLIENT_ID to "c8fcb3bf-22d3-44b0-b6ce-30eae0a4986f". With the integration "Volkswagen WeConnect" I still get the below error:
> 
> [volkswagencarnet.vw_connection] Failed to fetch VW-Group API tokens, API token request returned with status code 403

You need to clean __pycache and if you use Home Assistant you need to restart it.

**Comment by beschoenen** [comment]
> Hi all, I changed the XCLIENT_ID to "c8fcb3bf-22d3-44b0-b6ce-30eae0a4986f". With the integration "Volkswagen WeConnect" I still get the below error:
> 
> [volkswagencarnet.vw_connection] Failed to fetch VW-Group API tokens, API token request returned with status code 403

Test with the new 4.4.65 release!

**Comment by artspb** [comment]
4.4.65 works like a charm. Thanks so much for the prompt fix!

**Comment by dkitz** [comment]
For all who had the 403 error, please check you have the right media!
