### ISSUE TITLE
Login failed for VW account, Token exchange failed

### ISSUE THREAD

**Issue by haeuslesbauer** [robinostlund/volkswagencarnet#213]
The script stopped working again yesterday.

ERROR:vw_connection:Login failed for VW account, Token exchange failed
ERROR:vw_connection:Token exchange failed
Traceback (most recent call last):
  File "/home/pi/scripts/vw_connection.py", line 348, in _login
    raise Exception("Token exchange failed")
Exception: Token exchange failed
INFO:vw_connection:Something failed__

In Home Assistant they discuss if this is related to the shutdown of VW Carnet:
https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/507

**Comment by oliverrahner** [comment]
While fetching to retrieve user identity tokens from `https://tokenrefreshservice.apps.emea.vwapps.io/exchangeAuthCode`, a 401 response is received with the following payload:
```
{
   "description":"IdentityKit Response: 401 : {\"error\":\"invalid_client\",\"error_description\":\"Client authentication failed\"}",
   "errorCode":"IDENTITY_KIT_RESPONSE_ERROR"
}
```

I'm on it right now, let's see if I can get it fixed...
