### ISSUE TITLE
Integration robinostlund/volkswagencarnet> Repository structure for v4.4.64-beta2 is not compliant

### ISSUE THREAD

**Issue by michaeldjjohnson** [robinostlund/volkswagencarnet#230]
Tried to add to Custom repositories in HACs and received this error

**Comment by beschoenen** [comment]
This repo is not a home assistant integration.

**Comment by stickpin** [comment]
@michaeldjjohnson use this link: https://github.com/robinostlund/homeassistant-volkswagencarnet
