### ISSUE TITLE
Message: door_locked is not supported and door status no longer available

### ISSUE THREAD

**Issue by thomastitze** [robinostlund/volkswagencarnet#241]
Using v4.4.64 the door lock status seems not available. 
See this in the debug output:
DEBUG:volkswagencarnet.vw_dashboard:WVWZZZXXXXX Doors locked (BinarySensor:door_locked) is not supported
DEBUG:volkswagencarnet.vw_dashboard:WVWZZZXXXXX Doors locked is supported
DEBUG:volkswagencarnet.vw_dashboard:WVWZZZXXXXX Door closed left front is supported
DEBUG:volkswagencarnet.vw_dashboard:WVWZZZXXXXX Door closed right front is supported
DEBUG:volkswagencarnet.vw_dashboard:WVWZZZXXXXX Door closed left back is supported
DEBUG:volkswagencarnet.vw_dashboard:WVWZZZXXXXX Door closed right back is supported

Same thing with 'trunk_locked',
Windows closed status 'windows_closed' is supported and can be read
Any idea what could be wrong?

**Comment by oliverrahner** [comment]
This message should only appear if the related information cannot be found in the response we receive from the Volkswagen API… is this behavior consistent or does it only appear sometimes?

**Comment by thomastitze** [comment]
Found the reason for the missing value. For the new Volkswagen app a user needs to authenticate completely with an Identity card and the Ident app IDnow. Then the door status information are available and I can now open / close the car remotely. With the old app I could at least read the information without the need for a full authentication.
