### ISSUE TITLE
e-Manager is queried regardless of engine type

### ISSUE THREAD

**Issue by pattyland** [robinostlund/volkswagencarnet#4]
Hi,

as already reported in the HA component [here](https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/29), [here](https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/19) and [here](https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/34) this library is trying to gather data from the VW e-Manager regardless of the engine type, resulting in 400 error for non electric or hybrid cars.

There is an easy way to determine the engine type via Car-Net: When you query `https://www.volkswagen-car-net.com/portal/user/***/*****/-/mainnavigation/get-fully-loaded-cars` you get values for the specific engine types:

```"engineTypeCombustian":true,
            "engineTypeHybridOCU1":false,
            "engineTypeHybridOCU2":false,
            "engineTypeElectric":false,
            "engineTypeCNG":false,
            "engineTypeDefault":false,
```

You should use this data to determine wether you should query e-Manager or not

Greets,
Sören

**Comment by cyberjunky** [comment]
I had same issue, component doesn't work because of this.

This is my fix, wil generate pull request soon, have to fix other things
CombustionRange seems gone too, is now fuelRange, batteryRange, cngRange etc

```
                        _LOGGER.error('Failed to request vehicle update')

                if not vehicle['engineTypeCombustian']:
                    # fetch vehicle emanage data
                    try:
                        vehicle_emanager = self.post('-/emanager/get-emanager', rel)
                        if vehicle_emanager.get('errorCode', {}) == '0' and vehicle_emanager.get('EManager', {}):
                            self._state[vin]['emanager'] = vehicle_emanager.get('EManager', {})
                    except Exception as err:
                        _LOGGER.debug('Could not fetch emanager data: %s' % err)

                # fetch vehicle location data

**Comment by nicx** [comment]
that would be great, because I don't have an electric engine, too ;)
