### ISSUE TITLE
Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

### ISSUE THREAD

**Issue by nekman** [robinostlund/volkswagencarnet#7]
Hej,

Thanks for a great library!
I was trying to use the library on a AWS Lambda, but it failed with the following error message:
```
Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

Searched for the error on StackOverflow, and was recommended to install:
```
pip3 install et_xmlfile
pip3 uninstall lxml
pip3 install --upgrade lxml
```
But it did not help.

So, as a workaround I edited the `v-env/lib/python3.7/site-packages/volkswagencarnet.py` and replaced:

```diff
-bs = BeautifulSoup(req.text, 'lxml')
+bs = BeautifulSoup(req.text, 'html.parser')
```
on line 103 and 136. And after that it started to work. 

Is it possible for you to provide a better solution?
Perhaps, if lxml fails, catch the error and try with html.parser?

Thanks!

**Comment by nekman** [comment]
Also note that the library worked perfectly fine on my OSX. It was when I running it on AWS Lambda that I got the error.

**Comment by robinostlund** [comment]
Solved :)
