### ISSUE TITLE
Problem with carnet request

### ISSUE THREAD

**Issue by greberg** [robinostlund/volkswagencarnet#9]
In def _login it looks like this request req = self._session.get(self._session_base + 'portal/sv_SE/web/guest/home') creates this error:

Failed to login to carnet, HTTPSConnectionPool(host='www.portal.volkswagen-we.com', port=443): Max retries exceeded with url: //portal/sv_SE/web/guest/home (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

If I try to add in the request req = self._session.get(self._session_base + 'portal/sv_SE/web/guest/home', verify=False) it passes that request but fails on the post to https://www.portal.volkswagen-we.com/portal/web/guest/complete-login?p_auth=xxx&p_p_id=33_WAR_cored5portlet&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_33_WAR_cored5portlet_javax.portlet.action=getLoginStatus

Not really sure how to get it to work.

**Comment by Rayzilt** [comment]
There is a problem on the car-net side as the certificate is no longer accepted in Debian 10 and probably in other linux based os.

ssllabs.com reports an incomple certificate chain and so does curl also.

```
curl -vvI https://portal.volkswagen-we.com/portal/
----
*   Trying 3.124.225.187...
* TCP_NODELAY set
* Expire in 149947 ms for 3 (transfer 0x56183b4a8f50)
* Expire in 200 ms for 4 (transfer 0x56183b4a8f50)
* Connected to portal.volkswagen-we.com (3.124.225.187) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by matlimatli** [comment]
> There is a problem on the car-net side as the certificate is no longer accepted in Debian 10 and probably in other linux based os.

Yes, as a temporary workaround, I appended the missing cert from https://www.quovadisglobal.com/QVRepository/DownloadRootsAndCRL/QuoVadisGlobalSSLICAG3-PEM.aspx
to my local cacert.pem file (exact location given by certifi.where() in python). This made the component work again.  This is of course not the right solution, but at least it shows that this is indeed the problem.

**Comment by tubalainen** [comment]
> > There is a problem on the car-net side as the certificate is no longer accepted in Debian 10 and probably in other linux based os.
> 
> Yes, as a temporary workaround, I appended the missing cert from https://www.quovadisglobal.com/QVRepository/DownloadRootsAndCRL/QuoVadisGlobalSSLICAG3-PEM.aspx
> to my local cacert.pem file (exact location given by certifi.where() in python). This made the component work again. This is of course not the right solution, but at least it shows that this is indeed the problem.

Can confirm! Works great.

**Comment by HikingMike** [comment]
> > > There is a problem on the car-net side as the certificate is no longer accepted in Debian 10 and probably in other linux based os.
> > 
> > 
> > Yes, as a temporary workaround, I appended the missing cert from https://www.quovadisglobal.com/QVRepository/DownloadRootsAndCRL/QuoVadisGlobalSSLICAG3-PEM.aspx
> > to my local cacert.pem file (exact location given by certifi.where() in python). This made the component work again. This is of course not the right solution, but at least it shows that this is indeed the problem.
> 
> Can confirm! Works great.

Excellent! Works fine. Thanks alot. :)

**Comment by vlumikero** [comment]
Does anyone know if this is possible in hassio?

**Comment by greberg** [comment]
Yes works fine for me as well using docker. Thanks

**Comment by matlimatli** [comment]
> Yes works fine for me as well using docker. Thanks

Note that you will probably lose the change when upgrading your docker image. If VW haven't fixed their certificate chain by then, you will need to append the cert again.

(And if you use this method on a regular linux host, the cacert.pem will be overwritten on certain system updates. There are ways of making it more persistent if you like.)

I build my own docker image for home-assistant, and for now, I have added the following lines to my Dockerfile:
```
COPY qvsslicag3.pem /tmp/
RUN cat /tmp/qvsslicag3.pem >> `python -c 'import certifi; print(certifi.where())'` && rm /tmp/qvsslicag3.pem
```

**Comment by Konstigt** [comment]
For me, python -m certify showed this location:

```
$ python -m certifi
/home/homeassistant/homeassistant/lib/python3.7/site-packages/certifi/cacert.pem

```
But the file to change that made a difference was actually this:

`  /home/homeassistant/homeassistant/lib/python3.7/site-packages/pip/_vendor/certifi/cacert.pem`

**Comment by jonaswikstrom** [comment]
When I run the _python -m certifi_ command i get the following location:

/usr/local/lib/python3.7/site-packages/certifi/cacert.pem

Can't be right can it?

**Comment by andlo** [comment]
> Can't be right can it?
on my hassio it is eactly that, and it worked apending the certificate to that.

**Comment by jonaswikstrom** [comment]
Works like a cherm! Thanks!

**Comment by robinostlund** [comment]
Solved :)
