### ISSUE TITLE
potential issue in example code

### ISSUE THREAD

**Issue by vomov** [robinostlund/volkswagencarnet#91]
If I use the newer version (with asyncio), and start from the example, I get the following error:
`Failed to login to carnet, Response payload is not completed`

This can be fixed by using:
`headers={'Connection': 'keep-alive'}`
during ClientSession creation, like so:
`async with ClientSession(headers={'Connection': 'keep-alive'}) as session:`

**Comment by robinostlund** [comment]
Thanks i added that to the readme :)
