### ISSUE TITLE
Feature request: add support for Skoda Connect

### ISSUE THREAD

**Issue by DBa2016** [robinostlund/volkswagencarnet#93]
Skoda connect uses the same technology, only some URLs etc are different, so would be great to add support for it here!

**Comment by sbauza** [comment]
I already started to look at the API calls and indeed the returned objects are quite identical. I have a Skoda Connect account, I'll try to provide a PR if I have time.

**Comment by sbauza** [comment]
Actually, thinking it a bit more, we either have to make skodaconnect a specific package or make volkswagenconnect be more generic for VAG cars and exposing different options (per se, seat, skoda, vw, audi).

I've found another draft implementation for a automation tool named IOBroker, we can reuse the logic https://github.com/TA2k/ioBroker.vw-connect

**Comment by dkadioglu** [comment]
> I created a "skoda2mqtt" kind of thing using that iobroker adapter (because I am using a different smarthome solution and mqtt is much more universal), but it's really ugly. Maybe I'll publish it nevertheless.

Sounds great! I would really be interested in that. So, 👍 for publishing it.

**Comment by DBa2016** [comment]
I published a version here: https://github.com/DBa2016/sc2mqtt

This is work in progress,
