### ISSUE TITLE
Question: Does this work in the United States?

### ISSUE THREAD

**Issue by smockle** [robinostlund/volkswagencarnet#94]
I ran into an error using [robinostlund/volkswagencarnet-client](https://github.com/robinostlund/volkswagencarnet-client), and while debugging, I noticed this library’s `BASE_SESSION` variable is set to `https://www.portal.volkswagen-we.com/` ([`volkswagencarnet.py#L42`](https://github.com/robinostlund/volkswagencarnet/blob/2a1611cbe0f0f115f38b5fcfb715e485c1fe07c0/volkswagencarnet.py#L42)):
https://github.com/robinostlund/volkswagencarnet/blob/2a1611cbe0f0f115f38b5fcfb715e485c1fe07c0/volkswagencarnet.py#L42

As far as I know, the Volkswagen Car-Net portal in the United States (where my car is registered) is `https://carnet.vw.com/`.

When I attempt to log in on https://www.portal.volkswagen-we.com/, I’m asked for account information, including country/region, and “United States” is not included in the dropdown.

Am I correct in assuming that this library (and the projects which depend on it, e.g. [robinostlund/volkswagencarnet-client](https://github.com/robinostlund/volkswagencarnet-client) and [robinostlund/homeassistant-volkswagencarnet](https://github.com/robinostlund/homeassistant-volkswagencarnet)) does not support US-based accounts? Are you familiar with similar projects that do work in the United States?

**Comment by robinostlund** [comment]
Hi, that is true. Currently it is not supported as it doesnt use the same type of request. Unfortunately i havent seen any similar projects for now, but i hope that someone could look into it and help out in this project and make a pr for it.

**Comment by smockle** [comment]
Thanks for the confirmation @robinostlund! 👍

**Comment by danielwelch** [comment]
@smockle I looked into this and it looks like the heavy-lifting of figuring out the authentication flow for the US portal has already been done: `https://github.com/thomasesmith/vw-car-net-api`

Following that guide and adapting the code from this project, I've successfully logged in with python via the U.S. Portal and obtained a token. I haven't taken things any farther than that yet, but it would be great if everything else was similar and this project could be forked or expanded to include support for the U.S. login flow. Not sure how much interest there is for this.

**Comment by deep-daya** [comment]
Hey @danielwelch, do you mind sharing that code? I'm also trying to access my car from the US Portal, but am having difficulties in adapting this code to accept the US Code! If you want to make this a separate project, I would be happy to help out! Any help appreciated! 

Was the adaptation limited to changing the links in the vw_connection.py file?

**Comment by milkboy** [comment]
If the only change is different hosts, it should definitely be possible to add support for it, but PR:s from someone who can actually test it also would be nice.
